# Generated by Django 2.1.1 on 2018-09-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('nome', models.CharField(max_length=40)),
                ('matrícula', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=10)),
                ('observações', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20)),
                ('funçao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('notificacão', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='SelecionarPresencaseFaltas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
            options={
                'verbose_name_plural': 'SelecionarPresenças&Faltas',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('nome', models.CharField(max_length=40)),
                ('matricula', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servidor'),
        ),
    ]
