# Generated by Django 2.1.1 on 2018-09-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adicionar_justificativa_de_falta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicionar_justificativa_de_falta',
            options={'verbose_name_plural': 'Adicionar Justificativas de Faltas'},
        ),
    ]
