# Generated by Django 2.1.1 on 2018-09-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180919_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionar_justificativa_de_falta',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='Adicionar_Justificativa_de_Falta',
        ),
    ]
