# Generated by Django 2.1.1 on 2018-09-19 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180919_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionar_Justificativa_de_Falta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('Descrição', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
            options={
                'verbose_name_plural': 'Adicionar Justificativas de Faltas',
            },
        ),
    ]
