# Generated by Django 2.1.1 on 2018-09-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adicionar_justificativa_de_falta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerarDeclaracaoEstudantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('matrícula', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GerarListasDePresenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('nome_professor', models.CharField(max_length=40)),
                ('série', models.CharField(max_length=10)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
    ]
