# Generated by Django 2.1.1 on 2018-09-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gerardeclaracaoestudantil_gerarlistasdepresenca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gerardeclaracaoestudantil',
            options={'verbose_name_plural': 'Gerar Declarações Estudantis'},
        ),
        migrations.AlterModelOptions(
            name='gerarlistasdepresenca',
            options={'verbose_name_plural': 'Gerar Listas de Presença'},
        ),
    ]
