# Generated by Django 2.1.1 on 2018-09-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180919_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecionarpresencasefaltas',
            options={'verbose_name_plural': 'SelecionarPresenças e Faltas'},
        ),
    ]
